language: haskell
ghc: 7.6.3

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --force-yes cabal-install-1.22
#  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:/opt/cabal/1.20/bin:$PATH
  - cabal update
  - cabal install cabal-install
# - cabal install Cabal

install:
  - cabal --version
  - ghc --version
  - cabal install --only-dependencies --enable-tests --reorder-goals

script:
  - cabal configure --enable-tests && cabal build && cabal test

notifications:
  on_success: change
  on_failure: always
  on_start: false
