language: haskell
ghc: 7.6
sudo: false

install:
  - export PATH="/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH"
  - cabal sandbox init
  - cabal install --only-dependencies --enable-test

script:
  - cabal configure --enable-tests && cabal build && cabal test

notifications:
  on_success: change
  on_failure: always
  on_start: false
