language: haskell
ghc: 7.6.3

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --force-yes cabal-install-1.22
  - cabal install cabal-install

install:
  - export PATH=$HOME/.cabal/bin:$PATH
  - cabal --version
  - ghc --version
  - cabal install --only-dependencies --enable-tests --reorder-goals

script:
  - cabal configure --enable-tests && cabal build && cabal test

notifications:
  on_success: change
  on_failure: always
  on_start: false
